version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

  db:
    image: postgres:13.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"


  filldb:
    build:
      context: .
      dockerfile: DockerFile
    command: bash -c "python manage.py migrate && python manage.py loaddata fixture.json"
    links:
      - db:db
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

  linter:
    container_name: linter
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: bash -c "pip install -r requirements-dev.txt && flake8 --max-line-length 120 --exclude migrations,venv,manage.py"
    links:
      - db:db
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

  test:
    container_name: test
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python manage.py test
    links:
      - db:db
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

volumes:
  postgres_data:
  static_volume:
  media_volume: